name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: docker build -t bala336/node-docker-ci:latest .

      # Step 4: Push Docker Image
      - name: Push to Docker Hub
        run: docker push bala336/node-docker-ci:latest
